#!/usr/bin/env python3
"""Compatibility entry point for running ``python jemdoc``."""

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Yutao Tang.

from jemdoc import main


if __name__ == '__main__':
  main()
